In [72]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [73]:
pokemon = pd.read_csv("Pokedex_Ver_SV1.csv")
pokemon.head()

No Original_Name           Name  Generation Height   Weight  Type1   Type2  \
0   1     Bulbasaur      Bulbasaur           1   0.7m    6.9kg  Grass  Poison   
1   2       Ivysaur        Ivysaur           1   1.0m   13.0kg  Grass  Poison   
2   3      Venusaur       Venusaur           1   2.0m  100.0kg  Grass  Poison   
3   3      Venusaur  Mega Venusaur           1   2.4m  155.5kg  Grass  Poison   
4   4    Charmander     Charmander           1   0.6m    8.5kg   Fire     NaN   

    Ability1 Ability2  ... SP_Attack SP_Defense  Speed  Total  E_HP  E_Attack  \
0   Overgrow      NaN  ...        65         65     45    318     0         0   
1   Overgrow      NaN  ...        80         80     60    405     0         0   
2   Overgrow      NaN  ...       100        100     80    525     0         0   
3  Thick Fat      NaN  ...       122        120     80    625     0         0   
4      Blaze      NaN  ...        60         50     65    309     0         0   

  E_Defense E_SP_Attack  E_SP_Defense  E_Speed  
0         0           1             0        0  
1         0           1             1        0  
2         0           2             1        0  
3         0           2             1        0  
4         0           0             0        1  

[5 rows x 37 columns]

In [74]:
pokemon = pokemon.drop(["Original_Name", "Name", "Generation", "Ability1", "Ability2", "Ability_Hidden", "Color"], axis = 1)

In [75]:
pokemon.head()

No Height   Weight  Type1   Type2  Gender_Male  Gender_Female  \
0   1   0.7m    6.9kg  Grass  Poison         87.5           12.5   
1   2   1.0m   13.0kg  Grass  Poison         87.5           12.5   
2   3   2.0m  100.0kg  Grass  Poison         87.5           12.5   
3   3   2.4m  155.5kg  Grass  Poison         87.5           12.5   
4   4   0.6m    8.5kg   Fire     NaN         87.5           12.5   

   Gender_Unknown  Egg_Steps Egg_Group1  ... SP_Attack  SP_Defense  Speed  \
0               0         20    Monster  ...        65          65     45   
1               0         20    Monster  ...        80          80     60   
2               0         20    Monster  ...       100         100     80   
3               0         20    Monster  ...       122         120     80   
4               0         20    Monster  ...        60          50     65   

   Total E_HP E_Attack E_Defense  E_SP_Attack  E_SP_Defense  E_Speed  
0    318    0        0         0            1             0        0  
1    405    0        0         0            1             1        0  
2    525    0        0         0            2             1        0  
3    625    0        0         0            2             1        0  
4    309    0        0         0            0             0        1  

[5 rows x 30 columns]

In [76]:
pokemon = pokemon.drop(["Gender_Male", "Gender_Female", "Gender_Unknown", "Egg_Steps", "Egg_Group1", "Egg_Group2", "Region_Form"], axis = 1)

In [77]:
pokemon = pokemon.drop(["E_HP", "E_Attack", "E_Defense", "E_SP_Attack", "E_Speed", "E_SP_Defense"], axis = 1)
pokemon.head()

No Height   Weight  Type1   Type2  Get_Rate  Base_Experience  \
0   1   0.7m    6.9kg  Grass  Poison        45               64   
1   2   1.0m   13.0kg  Grass  Poison        45              142   
2   3   2.0m  100.0kg  Grass  Poison        45              263   
3   3   2.4m  155.5kg  Grass  Poison        45              281   
4   4   0.6m    8.5kg   Fire     NaN        45               62   

   Experience_Type  Category Mega_Evolution_Flag  HP  Attack  Defense  \
0          1059860  Ordinary                 NaN  45      49       49   
1          1059860  Ordinary                 NaN  60      62       63   
2          1059860  Ordinary                 NaN  80      82       83   
3          1059860  Ordinary                Mega  80     100      123   
4          1059860  Ordinary                 NaN  39      52       43   

   SP_Attack  SP_Defense  Speed  Total  
0         65          65     45    318  
1         80          80     60    405  
2        100         100     80    525  
3        122         120     80    625  
4         60          50     65    309

In [78]:
np.random.seed(3)

pokemon.fillna("No", inplace = True)

pokemon1 = pd.get_dummies(pokemon[["Type1", "Type2", "Mega_Evolution_Flag"]], )

In [79]:
pokemon1

Type1_Bug  Type1_Dark  Type1_Dragon  Type1_Electric  Type1_Fairy  \
0             0           0             0               0            0   
1             0           0             0               0            0   
2             0           0             0               0            0   
3             0           0             0               0            0   
4             0           0             0               0            0   
...         ...         ...           ...             ...          ...   
1188          0           0             0               0            0   
1189          0           0             0               0            0   
1190          0           1             0               0            0   
1191          0           0             0               0            0   
1192          0           0             0               0            0   

      Type1_Fighting  Type1_Fire  Type1_Flying  Type1_Ghost  Type1_Grass  ...  \
0                  0           0             0            0            1  ...   
1                  0           0             0            0            1  ...   
2                  0           0             0            0            1  ...   
3                  0           0             0            0            1  ...   
4                  0           1             0            0            0  ...   
...              ...         ...           ...          ...          ...  ...   
1188               0           0             0            0            0  ...   
1189               0           0             0            0            0  ...   
1190               0           0             0            0            0  ...   
1191               0           0             0            0            0  ...   
1192               1           0             0            0            0  ...   

      Type2_Ice  Type2_No  Type2_Normal  Type2_Poison  Type2_Psychic  \
0             0         0             0             1              0   
1             0         0             0             1              0   
2             0         0             0             1              0   
3             0         0             0             1              0   
4             0         1             0             0              0   
...         ...       ...           ...           ...            ...   
1188          0         0             0             0              0   
1189          0         0             0             0              0   
1190          0         0             0             0              0   
1191          0         0             0             0              0   
1192          0         0             0             0              0   

      Type2_Rock  Type2_Steel  Type2_Water  Mega_Evolution_Flag_Mega  \
0              0            0            0                         0   
1              0            0            0                         0   
2              0            0            0                         0   
3              0            0            0                         1   
4              0            0            0                         0   
...          ...          ...          ...                       ...   
1188           0            0            0                         0   
1189           0            0            0                         0   
1190           0            1            0                         0   
1191           0            0            0                         0   
1192           0            0            0                         0   

      Mega_Evolution_Flag_No  
0                          1  
1                          1  
2                          1  
3                          0  
4                          1  
...                      ...  
1188                       1  
1189                       1  
1190                       1  
1191                       1  
1192                       1  

[1193 rows x 39 columns]

In [80]:
pokemon.head()

No Height   Weight  Type1   Type2  Get_Rate  Base_Experience  \
0   1   0.7m    6.9kg  Grass  Poison        45               64   
1   2   1.0m   13.0kg  Grass  Poison        45              142   
2   3   2.0m  100.0kg  Grass  Poison        45              263   
3   3   2.4m  155.5kg  Grass  Poison        45              281   
4   4   0.6m    8.5kg   Fire      No        45               62   

   Experience_Type  Category Mega_Evolution_Flag  HP  Attack  Defense  \
0          1059860  Ordinary                  No  45      49       49   
1          1059860  Ordinary                  No  60      62       63   
2          1059860  Ordinary                  No  80      82       83   
3          1059860  Ordinary                Mega  80     100      123   
4          1059860  Ordinary                  No  39      52       43   

   SP_Attack  SP_Defense  Speed  Total  
0         65          65     45    318  
1         80          80     60    405  
2        100         100     80    525  
3        122         120     80    625  
4         60          50     65    309

In [81]:
pokemon = pd.concat([pokemon.drop(["Type1", "Type2", "Mega_Evolution_Flag"], axis=1), pokemon1], axis=1)
pokemon

No Height   Weight  Get_Rate  Base_Experience  Experience_Type  \
0        1   0.7m    6.9kg        45               64          1059860   
1        2   1.0m   13.0kg        45              142          1059860   
2        3   2.0m  100.0kg        45              263          1059860   
3        3   2.4m  155.5kg        45              281          1059860   
4        4   0.6m    8.5kg        45               62          1059860   
...    ...    ...      ...       ...              ...              ...   
1188  1006   0.9m   33.0kg       190               67          1059860   
1189  1007   1.9m   58.0kg        90              180          1059860   
1190  1008   2.0m  120.0kg        25              275          1000000   
1191  1009   1.8m  223.0kg        90              151          1000000   
1192  1010   1.2m   56.0kg        45              268          1000000   

      Category   HP  Attack  Defense  ...  Type2_Ice  Type2_No  Type2_Normal  \
0     Ordinary   45      49       49  ...          0         0             0   
1     Ordinary   60      62       63  ...          0         0             0   
2     Ordinary   80      82       83  ...          0         0             0   
3     Ordinary   80     100      123  ...          0         0             0   
4     Ordinary   39      52       43  ...          0         1             0   
...        ...  ...     ...      ...  ...        ...       ...           ...   
1188  Ordinary   40      40       35  ...          0         0             0   
1189  Ordinary   80      70       65  ...          0         0             0   
1190  Ordinary  100     135      120  ...          0         0             0   
1191  Ordinary  130      75       60  ...          0         0             0   
1192  Ordinary  110     115       80  ...          0         0             0   

      Type2_Poison  Type2_Psychic  Type2_Rock  Type2_Steel  Type2_Water  \
0                1              0           0            0            0   
1                1              0           0            0            0   
2                1              0           0            0            0   
3                1              0           0            0            0   
4                0              0           0            0            0   
...            ...            ...         ...          ...          ...   
1188             0              0           0            0            0   
1189             0              0           0            0            0   
1190             0              0           0            1            0   
1191             0              0           0            0            0   
1192             0              0           0            0            0   

      Mega_Evolution_Flag_Mega  Mega_Evolution_Flag_No  
0                            0                       1  
1                            0                       1  
2                            0                       1  
3                            1                       0  
4                            0                       1  
...                        ...                     ...  
1188                         0                       1  
1189                         0                       1  
1190                         0                       1  
1191                         0                       1  
1192                         0                       1  

[1193 rows x 53 columns]

In [82]:
pokemon["Height"] = pokemon["Height"].str.replace("m", "")
pokemon["Weight"] = pokemon["Weight"].str.replace("kg", "")
pokemon

No Height Weight  Get_Rate  Base_Experience  Experience_Type  \
0        1    0.7    6.9        45               64          1059860   
1        2    1.0   13.0        45              142          1059860   
2        3    2.0  100.0        45              263          1059860   
3        3    2.4  155.5        45              281          1059860   
4        4    0.6    8.5        45               62          1059860   
...    ...    ...    ...       ...              ...              ...   
1188  1006    0.9   33.0       190               67          1059860   
1189  1007    1.9   58.0        90              180          1059860   
1190  1008    2.0  120.0        25              275          1000000   
1191  1009    1.8  223.0        90              151          1000000   
1192  1010    1.2   56.0        45              268          1000000   

      Category   HP  Attack  Defense  ...  Type2_Ice  Type2_No  Type2_Normal  \
0     Ordinary   45      49       49  ...          0         0             0   
1     Ordinary   60      62       63  ...          0         0             0   
2     Ordinary   80      82       83  ...          0         0             0   
3     Ordinary   80     100      123  ...          0         0             0   
4     Ordinary   39      52       43  ...          0         1             0   
...        ...  ...     ...      ...  ...        ...       ...           ...   
1188  Ordinary   40      40       35  ...          0         0             0   
1189  Ordinary   80      70       65  ...          0         0             0   
1190  Ordinary  100     135      120  ...          0         0             0   
1191  Ordinary  130      75       60  ...          0         0             0   
1192  Ordinary  110     115       80  ...          0         0             0   

      Type2_Poison  Type2_Psychic  Type2_Rock  Type2_Steel  Type2_Water  \
0                1              0           0            0            0   
1                1              0           0            0            0   
2                1              0           0            0            0   
3                1              0           0            0            0   
4                0              0           0            0            0   
...            ...            ...         ...          ...          ...   
1188             0              0           0            0            0   
1189             0              0           0            0            0   
1190             0              0           0            1            0   
1191             0              0           0            0            0   
1192             0              0           0            0            0   

      Mega_Evolution_Flag_Mega  Mega_Evolution_Flag_No  
0                            0                       1  
1                            0                       1  
2                            0                       1  
3                            1                       0  
4                            0                       1  
...                        ...                     ...  
1188                         0                       1  
1189                         0                       1  
1190                         0                       1  
1191                         0                       1  
1192                         0                       1  

[1193 rows x 53 columns]

In [83]:
X = pokemon.drop("Category", axis = 1)
y = pokemon["Category"]

X_train, X_test, y_train, y_test = train_test_split(X, y)

clf = RandomForestClassifier()

clf.fit(X_train, y_train)

y_preds = clf.predict(X_test)

clf.score(X_test, y_test)

0.979933110367893

In [84]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_preds))

# Classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_preds))

[[ 10   0   1   0]
 [  2   6   0   1]
 [  0   0 254   1]
 [  1   0   0  23]]
                precision    recall  f1-score   support

     Legendary       0.77      0.91      0.83        11
      Mythical       1.00      0.67      0.80         9
      Ordinary       1.00      1.00      1.00       255
Semi-Legendary       0.92      0.96      0.94        24

      accuracy                           0.98       299
     macro avg       0.92      0.88      0.89       299
  weighted avg       0.98      0.98      0.98       299

